#!/usr/bin/env bash
## Post-deploy: enable/mask user-level systemd units
##
## Reads services.list generated by the systemd build-time shim, filters
## for user-scope entries, and applies each via systemctl --user.
## User-level service management requires a running user manager,
## which is not available during container builds.
set -euo pipefail

SERVICES_LIST="/usr/share/system-state.d/systemd/services.list"

[[ -f "$SERVICES_LIST" ]] || exit 0

while IFS=$'\t' read -r unit state scope; do
    [[ "$scope" == "user" ]] || continue
    [[ -n "$unit" && -n "$state" ]] || continue
    case "$state" in
        enabled) systemctl --user enable "$unit" ;;
        masked)  systemctl --user mask "$unit" ;;
        *)
            echo "WARNING: systemd post-deploy: unknown state '$state' for $unit" >&2
            continue
            ;;
    esac
done < "$SERVICES_LIST"
